#pragma once

#define LED_BLUE_PORT GPIOB
#define LED_BLUE_PIN 13

#define LED_GREEN_PORT GPIOA
#define LED_GREEN_PIN 8

#define NERNST_ESR_DRIVER_PORT GPIOB
#define NERNST_ESR_DRIVER_PIN 12

// PC13
#define HEATER_PWM_DEVICE PWMD1
#define HEATER_PWM_CHANNEL 0

// PA1 TIM2_CH2
#define PUMP_DAC_PWM_DEVICE PWMD2
#define PUMP_DAC_PWM_CHANNEL 1


// USART1 TX PA9
// USART1 RX PA10
