#pragma once

#define BLUE_LED_PORT GPIOB
#define BLUE_LED_PIN 5

#define GREEN_LED_PORT GPIOB
#define GREEN_LED_PIN 6

#define NERNST_ESR_DRIVER_PORT GPIOB
#define NERNST_ESR_DRIVER_PIN 7

#define HEATER_PWM_DEVICE PWMD1
#define HEATER_PWM_CHANNEL 0

#define PUMP_DAC_PWM_DEVICE PWMD3
#define PUMP_DAC_PWM_CHANNEL 0
