#pragma once

#define LED_BLUE_PORT GPIOB
#define LED_BLUE_PIN 5

#define LED_GREEN_PORT GPIOB
#define LED_GREEN_PIN 6

#define NERNST_49_ESR_DRIVER_PORT GPIOB
#define NERNST_49_ESR_DRIVER_PIN 7

// PA7
#define HEATER_PWM_DEVICE PWMD1
#define HEATER_PWM_CHANNEL_0 0

// PA6
#define PUMP_DAC_PWM_DEVICE PWMD3
#define PUMP_DAC_PWM_CHANNEL_0 0

#define ID_SEL1_PORT GPIOB
#define ID_SEL1_PIN 1

#define ID_SEL2_PORT GPIOA
#define ID_SEL2_PIN 8
